name: "Run Custom Shell Script"
description: "Runs a shell script with username, password and google api key"
author: "DAC coustom action"
inputs:
        api_url:
          description: "API URL to use"
          required: true
          default: "osh-preprod.oneapihub.com"


runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install sanity check dependencies
      run: pip install pyyaml openapi-spec-validator
      shell: bash

    - name: Run OpenAPI sanity check
      run: python ${{ github.action_path }}/sanity_check_openapi.py
      shell: bash

    - name: Set up dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq zip

    - name: Get changed Api_Document folders
      id: changed_folders
      shell: bash
      run: |
        git fetch --no-tags --prune --depth=2 origin main

        mapfile -t changed_folders < <(
          git diff --name-only --diff-filter=AM HEAD~1 HEAD |
          grep '^Api_Document/' |
          awk -F/ '{print $2}' |
          sort -u
        )

        echo "✅ Changed folders in Api_Document:"
        printf '%s\n' "${changed_folders[@]}"

        changed_arg=$(printf '%s ' "${changed_folders[@]}")
        changed_arg="${changed_arg%" "}"  # remove trailing space

        echo "CHANGED_FOLDERS=$changed_arg" >> $GITHUB_ENV

    - name: Make script executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/dsh_upload.sh

    - name: Run script with inputs and changed folders
      shell: bash
      run: ${{ github.action_path }}/dsh_upload.sh $CHANGED_FOLDERS
